name: Update Files From Multiple Repos

on:
  repository_dispatch:
    types: [update-files]
  workflow_dispatch:       # lets you run it manually

permissions:
  contents: write

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pages repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: master

      - name: Check CV repo
        uses: actions/checkout@v4
        with:
          repository: waitingsze/job-market
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: cv

      - name: Check JMP repo
        uses: actions/checkout@v4
        with:
          repository: waitingsze/chapter1
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: jmp

      - name: Copy files to files folder
        run: |
          mkdir -p files
          cp cv/cv/cv.pdf files/sze_waiting_cv.pdf
          cp jmp/paper/main.pdf files/sze_waiting_jmp.pdf

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add files/*.pdf
          if ! git diff --cached --quiet; then
            git commit -m "Updated files"
            git push origin master
          else
            echo "No changes to commit."
          fi
